-- ---------------------------------------------------------------------------
-- Fleet Manager — Configuração do Supabase Storage
-- ---------------------------------------------------------------------------
-- Cria o bucket usado para armazenar os arquivos anexados aos documentos.
--
-- Como executar: painel do Supabase > SQL Editor > New query > colar > Run.
--
-- ATENÇÃO — a configuração do Storage tem DUAS ETAPAS:
--   Etapa 1 (este arquivo)  — criação do bucket, por SQL.
--   Etapa 2 (painel)        — criação das políticas de acesso, pela interface
--                             Storage > Policies. As instruções completas
--                             estão no final deste arquivo.
--
-- Por que as políticas não estão neste script:
--   A tabela `storage.objects` pertence ao papel `supabase_storage_admin`. O
--   PostgreSQL exige ser dono da tabela para criar políticas sobre ela, e o
--   papel `postgres` — usado pelo SQL Editor — não é dono nem pode assumir
--   aquele papel. As duas tentativas por SQL falham:
--
--     ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
--       -> ERROR: 42501: must be owner of table objects
--
--     SET ROLE supabase_storage_admin;
--       -> ERROR: 42501: permission denied to set role "supabase_storage_admin"
--
--   O caminho suportado pela plataforma é a interface Storage > Policies, que
--   executa a criação com o papel adequado. O SQL equivalente está registrado
--   ao final, em comentário, para servir de referência.
--
--   Observação: não é necessário habilitar o RLS em `storage.objects` — ele já
--   vem habilitado por padrão nos projetos Supabase.
-- ---------------------------------------------------------------------------

-- Etapa 1 — Bucket público de documentos ------------------------------------
-- Público: os arquivos são exibidos na aplicação por URL direta
-- (getPublicUrl), sem necessidade de assinatura.
insert into storage.buckets (id, name, public)
values ('documents', 'documents', true)
on conflict (id) do update set public = true;


-- ===========================================================================
-- Etapa 2 — Políticas de acesso (criar pelo painel)
-- ===========================================================================
-- Caminho: Storage > Policies > bucket `documents` > New policy
--          > "For full customization"
--
-- A interface permite marcar várias operações em uma mesma política, de modo
-- que duas políticas cobrem todo o uso do sistema.
--
-- Observação da interface: ao marcar UPDATE ou DELETE, o Supabase marca
-- SELECT automaticamente e informa que "UPDATE and DELETE require it". Isso
-- está correto e deve ser mantido — ambas as operações precisam localizar o
-- objeto antes de alterá-lo ou removê-lo. Desmarcar o SELECT depois de criar
-- a política faz a remoção de arquivos falhar.
--
-- ---------------------------------------------------------------------------
-- POLÍTICA 1 — Envio de arquivos
--   Nome              : Allow authenticated document uploads
--   Allowed operation : INSERT   (apenas esta)
--   Target roles      : authenticated
--   WITH CHECK        :
--
--       bucket_id = 'documents'
--       and storage.extension(name) in ('jpg','jpeg','png','webp','pdf')
--
--   Fica isolada porque é a única que carrega a restrição de extensões, que
--   não faria sentido nas demais operações.
--
--   Essa restrição é a ÚNICA validação de tipo de arquivo do sistema, já que
--   o upload não passa pela API. Se for omitida, o sistema continua
--   funcionando, porém aceitará qualquer tipo de arquivo.
--
-- ---------------------------------------------------------------------------
-- POLÍTICA 2 — Leitura, substituição e remoção
--   Nome              : Allow authenticated document management
--   Allowed operation : SELECT, UPDATE, DELETE
--   Target roles      : authenticated
--   USING             : bucket_id = 'documents'
--   WITH CHECK        : bucket_id = 'documents'
--
-- ---------------------------------------------------------------------------
-- Leitura anônima não requer política: o bucket é público, portanto os
-- arquivos exibidos por getPublicUrl são servidos sem passar por RLS.
--
-- ===========================================================================
-- SQL equivalente (referência — não executável pelo SQL Editor)
-- ===========================================================================
-- Registrado para documentar exatamente o que a interface cria. Só funciona
-- em uma conexão com privilégios de `supabase_storage_admin`.
--
--   create policy "Allow authenticated document uploads"
--   on storage.objects for insert to authenticated
--   with check (
--     bucket_id = 'documents'
--     and storage.extension(name) in ('jpg','jpeg','png','webp','pdf')
--   );
--
--   create policy "Allow authenticated document management"
--   on storage.objects for all to authenticated
--   using (bucket_id = 'documents')
--   with check (bucket_id = 'documents');
-- ===========================================================================
