-- ---------------------------------------------------------------------------
-- Fleet Manager — Configuração do Supabase Storage
-- ---------------------------------------------------------------------------
-- Os arquivos anexados aos documentos ficam no bucket `documents`.
--
-- O estado correto do bucket é: PRIVADO e SEM POLÍTICA ALGUMA. Não é
-- configuração pela metade — é o desenho. Com RLS habilitada (padrão do
-- Supabase) e nenhuma política, `anon` e `authenticated` não alcançam nada, e
-- só a `service_role` passa. Quem usa a `service_role` é a API, que aplica o
-- recorte de acesso antes de assinar qualquer URL.
--
-- Como executar: painel do Supabase > SQL Editor > New query > colar > Run.
-- ---------------------------------------------------------------------------


-- ===========================================================================
-- Configuração — projeto novo
-- ===========================================================================
-- Único comando necessário. Nenhuma política é criada depois dele.
insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do update set public = false;


-- ===========================================================================
-- Conferência
-- ===========================================================================
--   select id, public from storage.buckets where id = 'documents';
--   -- public deve ser false
--
--   select policyname, cmd, roles
--   from pg_policies
--   where schemaname = 'storage' and tablename = 'objects';
--   -- nenhuma linha para o bucket `documents`
--
-- Na aplicação, com o token de uma motorista:
--
--   POST /storage/v1/object/sign/documents/<caminho>   -> 400 NoSuchKey
--   GET  /api/documents/<id dela>/arquivo              -> 200 { url }
--   GET  /api/documents/<id de um colega>/arquivo      -> 404
--
-- O 400 vale inclusive para o anexo dela própria: o navegador não alcança o
-- bucket, e é isso que se espera. Todo anexo passa pela API.


-- ===========================================================================
-- Por que nenhuma política — o histórico
-- ===========================================================================
-- Duas configurações anteriores foram abandonadas. Ficam registradas porque a
-- ausência de política parece, à primeira vista, um passo esquecido.
--
-- ---------------------------------------------------------------------------
-- 1ª — bucket público, políticas só para `authenticated`  (INSEGURA)
-- ---------------------------------------------------------------------------
-- A única condição era `bucket_id = 'documents'`. Nenhuma menção a empresa,
-- dono ou caminho:
--
--     SELECT / UPDATE / DELETE  ->  using (bucket_id = 'documents')
--     INSERT                    ->  with check (bucket_id = 'documents' and
--                                   storage.extension(name) in (...))
--
-- Qualquer usuário do sistema listava, baixava, sobrescrevia e apagava anexo
-- de QUALQUER empresa, falando direto com a API do Storage. E o bucket era
-- público, o que permitia leitura anônima de posse da URL.
--
-- ---------------------------------------------------------------------------
-- 2ª — bucket privado, políticas recortando por empresa  (INSUFICIENTE)
-- ---------------------------------------------------------------------------
-- O caminho passou a começar pelo identificador da empresa
-- (`<companyId>/<entityId>/<uuid>.<ext>`) e as políticas chamavam
-- `public.pode_acessar_documentos()`, da migration 0005:
--
--     bucket_id = 'documents'
--     and public.pode_acessar_documentos((storage.foldername(name))[1])
--
-- Fechou o buraco maior, mas o recorte era POR EMPRESA — e a regra da
-- aplicação é mais estreita: o motorista alcança os próprios documentos
-- pessoais e os dos veículos a que está vinculado, não a CNH de um colega da
-- mesma empresa. Um motorista contornava a API e a política deixava passar.
--
-- Reproduzir a regra inteira em RLS significaria reescrevê-la em SQL, em
-- duplicata com o serviço que já a aplica. Duas cópias divergem.
--
-- ---------------------------------------------------------------------------
-- 3ª — a atual: o Storage sai do alcance do navegador
-- ---------------------------------------------------------------------------
-- As seis políticas que existiam foram apagadas pelo painel:
--
--     documentos_alterar_da_propria_empresa flreew_0    (UPDATE)
--     documentos_alterar_da_propria_empresa flreew_1    (SELECT)
--     documentos_enviar_para_a_propria_empresa flreew_0 (INSERT)
--     documentos_ler_da_propria_empresa flreew_0        (SELECT)
--     documentos_remover_da_propria_empresa flreew_0    (DELETE)
--     documentos_remover_da_propria_empresa flreew_1    (SELECT)
--
-- No lugar delas, a API:
--
--     GET  /documents/:id/arquivo           -> { url } de leitura, 60s
--     POST /documents/arquivo/url-de-envio  -> { url, caminho } de envio
--
-- A leitura reaproveita o mesmo `getDocument` da consulta — o que está fora do
-- alcance de quem pede devolve 404 e nunca chega a ser assinado. A regra não é
-- reescrita em lugar nenhum. No envio, a empresa do caminho vem do recorte de
-- acesso, nunca do corpo da requisição, e as extensões aceitas passaram a ser
-- conferidas pela API.
--
-- `public.pode_acessar_documentos()` ficou sem uso e foi removida pela
-- migration 0006 — depois das políticas, não junto: apagá-la antes derrubaria
-- as políticas que ainda a chamavam.
--
-- ---------------------------------------------------------------------------
-- Por que as políticas são mexidas pelo painel, e não por SQL
-- ---------------------------------------------------------------------------
-- `storage.objects` pertence ao papel `supabase_storage_admin`. O PostgreSQL
-- exige ser dono da tabela para criar ou apagar política sobre ela, e o papel
-- `postgres` — usado pelo SQL Editor — não é dono nem pode assumir aquele
-- papel:
--
--     ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
--       -> ERROR: 42501: must be owner of table objects
--
--     SET ROLE supabase_storage_admin;
--       -> ERROR: 42501: permission denied to set role "supabase_storage_admin"
--
-- Por isso a etapa de políticas nunca virou migration. Hoje isso não pesa:
-- não há política a criar.
-- ===========================================================================
