-- ---------------------------------------------------------------------------
-- Fleet Manager — Configuração do Supabase Storage
-- ---------------------------------------------------------------------------
-- Cria o bucket usado para armazenar os arquivos anexados aos documentos.
--
-- Como executar: painel do Supabase > SQL Editor > New query > colar > Run.
--
-- ATENÇÃO — a configuração do Storage tem DUAS ETAPAS:
--   Etapa 1 (este arquivo)  — criação do bucket, por SQL.
--   Etapa 2 (painel)        — criação das políticas de acesso, pela interface
--                             Storage > Policies. As instruções completas
--                             estão no final deste arquivo.
--
-- Por que as políticas não estão neste script:
--   A tabela `storage.objects` pertence ao papel `supabase_storage_admin`. O
--   PostgreSQL exige ser dono da tabela para criar políticas sobre ela, e o
--   papel `postgres` — usado pelo SQL Editor — não é dono nem pode assumir
--   aquele papel. As duas tentativas por SQL falham:
--
--     ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;
--       -> ERROR: 42501: must be owner of table objects
--
--     SET ROLE supabase_storage_admin;
--       -> ERROR: 42501: permission denied to set role "supabase_storage_admin"
--
--   O caminho suportado pela plataforma é a interface Storage > Policies, que
--   executa a criação com o papel adequado. O SQL equivalente está registrado
--   ao final, em comentário, para servir de referência.
--
--   Observação: não é necessário habilitar o RLS em `storage.objects` — ele já
--   vem habilitado por padrão nos projetos Supabase.
-- ---------------------------------------------------------------------------

-- Etapa 1 — Bucket público de documentos ------------------------------------
-- Público: os arquivos são exibidos na aplicação por URL direta
-- (getPublicUrl), sem necessidade de assinatura.
insert into storage.buckets (id, name, public)
values ('documents', 'documents', true)
on conflict (id) do update set public = true;


-- ===========================================================================
-- Etapa 2 — Políticas de acesso (criar pelo painel)
-- ===========================================================================
-- Caminho: Storage > Policies > bucket `documents` > New policy
--          > "For full customization"
--
-- A interface permite marcar várias operações em uma mesma política, de modo
-- que duas políticas cobrem todo o uso do sistema.
--
-- Observação da interface: ao marcar UPDATE ou DELETE, o Supabase marca
-- SELECT automaticamente e informa que "UPDATE and DELETE require it". Isso
-- está correto e deve ser mantido — ambas as operações precisam localizar o
-- objeto antes de alterá-lo ou removê-lo. Desmarcar o SELECT depois de criar
-- a política faz a remoção de arquivos falhar.
--
-- ATENÇÃO — a interface cria UMA POLÍTICA POR OPERAÇÃO marcada, acrescentando
-- um sufixo ao nome informado (`_0`, `_1`, `_2`). Por isso, marque TODAS as
-- operações da política 2 numa mesma submissão.
--
-- Criar UPDATE e depois DELETE em submissões separadas falha, porque cada
-- submissão tenta gerar novamente a política de SELECT com o mesmo nome:
--
--     ERROR: 42710: policy "<nome>_0" for table "objects" already exists
--
-- Se isso ocorrer, apague as políticas já criadas para o bucket e recomece,
-- marcando as três operações de uma vez.
--
-- ---------------------------------------------------------------------------
-- POLÍTICA 1 — Envio de arquivos
--   Nome              : Allow authenticated document uploads
--   Allowed operation : INSERT   (apenas esta)
--   Target roles      : authenticated
--   WITH CHECK        :
--
--       bucket_id = 'documents'
--       and storage.extension(name) in ('jpg','jpeg','png','webp','pdf')
--
--   Fica isolada porque é a única que carrega a restrição de extensões, que
--   não faria sentido nas demais operações.
--
--   Essa restrição é a ÚNICA validação de tipo de arquivo do sistema, já que
--   o upload não passa pela API. Se for omitida, o sistema continua
--   funcionando, porém aceitará qualquer tipo de arquivo.
--
-- ---------------------------------------------------------------------------
-- POLÍTICA 2 — Leitura, substituição e remoção
--   Nome              : Allow authenticated document management
--   Allowed operation : SELECT, UPDATE, DELETE
--   Target roles      : authenticated
--   USING             : bucket_id = 'documents'
--   WITH CHECK        : bucket_id = 'documents'
--
-- ---------------------------------------------------------------------------
-- Leitura anônima não requer política: o bucket é público, portanto os
-- arquivos exibidos por getPublicUrl são servidos sem passar por RLS.
--
-- ===========================================================================
-- SQL equivalente (referência — não executável pelo SQL Editor)
-- ===========================================================================
-- Registrado para documentar exatamente o que a interface cria. Só funciona
-- em uma conexão com privilégios de `supabase_storage_admin`.
--
--   create policy "Allow authenticated document uploads"
--   on storage.objects for insert to authenticated
--   with check (
--     bucket_id = 'documents'
--     and storage.extension(name) in ('jpg','jpeg','png','webp','pdf')
--   );
--
--   create policy "Allow authenticated document management"
--   on storage.objects for all to authenticated
--   using (bucket_id = 'documents')
--   with check (bucket_id = 'documents');
-- ===========================================================================

-- ===========================================================================
-- ATUALIZAÇÃO — recorte por empresa
-- ===========================================================================
-- As políticas registradas acima estão OBSOLETAS e eram inseguras: a única
-- condição era `bucket_id = 'documents'`, sem nenhuma menção a empresa, dono ou
-- caminho. Qualquer usuário autenticado alcançava, listava, sobrescrevia e
-- apagava anexo de qualquer empresa, falando direto com a API do Storage.
--
-- O que mudou:
--
--   1. O caminho do arquivo passou a começar pelo identificador da empresa:
--      `<companyId>/<entityId>/<uuid>.<ext>`. Sem isso, nenhuma política teria
--      de onde tirar a empresa dona do arquivo.
--
--   2. O bucket passou a ser PRIVADO. A leitura usa URL assinada de validade
--      curta (`createSignedUrl`), gerada na abertura do anexo.
--
--   3. A autorização passou a ser decidida por `public.pode_acessar_documentos`,
--      criada na migration 0005. Ela é `security definer` porque uma política do
--      Storage é avaliada como o papel `authenticated`, que não tem privilégio
--      algum sobre `public.users` — uma consulta direta falharia antes da RLS.
--
-- Passo a passo no painel
-- -----------------------
--   Storage > documents > Edit bucket  -> desmarcar "Public bucket"
--   Storage > Policies                 -> apagar as políticas antigas e criar
--                                         as quatro abaixo, com target role
--                                         `authenticated`
--
-- SELECT / UPDATE / DELETE  — expressão USING:
--
--   bucket_id = 'documents'
--   and public.pode_acessar_documentos((storage.foldername(name))[1])
--
-- INSERT — expressão WITH CHECK:
--
--   bucket_id = 'documents'
--   and public.pode_acessar_documentos((storage.foldername(name))[1])
--   and storage.extension(name) = any (array['jpg','jpeg','png','webp','pdf'])
--
-- No UPDATE, o painel grava apenas o USING. Não é problema: sem WITH CHECK, o
-- PostgreSQL aplica a expressão do USING também à linha nova — mover um arquivo
-- para o prefixo de outra empresa continua barrado.
--
-- Conferência
-- -----------
-- Simulando um usuário autenticado, sem precisar da interface:
--
--   begin;
--     set local role authenticated;
--     set local request.jwt.claims = '{"sub":"<auth_user_id>","role":"authenticated"}';
--     select public.pode_acessar_documentos('<company_id da propria empresa>');  -- true
--     select public.pode_acessar_documentos('<company_id de outra empresa>');    -- false
--   rollback;
-- ===========================================================================
