-- AlterTable
ALTER TABLE "Document" ADD COLUMN     "fileUrl" TEXT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "cpf" DROP DEFAULT,
ALTER COLUMN "phone" DROP DEFAULT,
ALTER COLUMN "passwordHash" DROP DEFAULT,
ALTER COLUMN "addressStreet" DROP DEFAULT,
ALTER COLUMN "addressNumber" DROP DEFAULT,
ALTER COLUMN "addressDistrict" DROP DEFAULT,
ALTER COLUMN "addressCity" DROP DEFAULT,
ALTER COLUMN "addressState" DROP DEFAULT,
ALTER COLUMN "addressZip" DROP DEFAULT;
